name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    uses: exbotanical/.github/.github/workflows/pnpm_script_run.yml@master
    with:
      script_name: lint

  stylelint:
    uses: exbotanical/.github/.github/workflows/pnpm_script_run.yml@master
    with:
      script_name: lint:css

  typecheck:
    uses: exbotanical/.github/.github/workflows/pnpm_script_run.yml@master
    with:
      script_name: typecheck

  unit_test:
    uses: exbotanical/.github/.github/workflows/pnpm_script_run.yml@master
    with:
      script_name: test:unit

  # TODO run in parallel
  # TODO test on different browsers
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Run Integration tests
        uses: cypress-io/github-action@v4.1.0
        with:
          install: false
          build: pnpm build
          start: pnpm serve
        env:
          CYPRESS_SUPPORT: 'y'
